#!/usr/bin/python3

#
#
#

import os
import random
import sys

#
#
#

version				= 'InDev Version 3'

nouns				= [
    'milkshake',
    'rock',
    'barbequeue',
    'brontosaurus',
    'Tyrannosaurus Rex',
    'soda',
    'microwave',
    'oven',
    'toilet',
    'sink',
    'TV',
    'camera',
    'Cheerios',
    'airplane',
    'nose',
    'egg',
    'heat',
    'bunny',
    'chainsaw',
    'flamethrower',
    'binoculars',
    'telescope',
    'iPod',
    'clock',
    'fireplace',
    'big rig',
    'truck',
    'car',
    'iPad',
    'newspaper',
    'printer',
]

verbs				= [
    'explodes',
    'flies',
    'falls',
    'crawls',
    'crashes',
    'flushes',
    'overflows',
    'bloats',
    'shrieks',
    'eats',
    'grills',
    'ages',
    'bursts',
    'burns',
    'holds',
    'wields',
    'cooks',
    'reads',
    'gasps',  
    'flexes',
]

adjectives			= [
    'delicious',
    'pointy',
    'bright',
    'ugly',
    'stupid',
    'poor',
    'expensive',
    'moist',
    'runny',
    'metallic',
    'hairy',
    'moldy',
    'tubular',
    'extreme',  
    
]




adverbs				= [
    'outrageously',
    'mathematically',
    'unwisely',
    'wisely',
    'blindly',
    'weakly',
    'strongly',
    'pathetically',
    'theoretically',
    'mysteriously',
    'provocatively',
    'stunningly',
    'magically',
    'wildly',
    'logically',
    'illogically',
]

articles			= [
    'The',
    'Your',
    "Your mother's",
    "Your father's",
    "Your sister's",
    "Your brother's",
    'My',
    "Your grandmother's",
    "Your grandfather's",
]

prepositions			= [
    'into',
    'out of',
]

prep_nouns			= [
    'pieces',
    'flames'
]

LOLZ				= [
    'LOLZ',
    'KIT KAT',
    'EPICNESS',
    'BANANAZ',
    'PEANUT BUTER JELLY TIME!!',
    'CHEZBURGER',
    'CREEPERS GONA CREEP',
    'BLENDERZ',
    'VEGIBURGERZ',
    'SUPER TOILET',
    'WAFLZ',
    'NYAN CAT',
    'CHICKEN WAFLE',
    'OMG HAX!!',
]

#
#
#

def run_game():
    count			= 1

    while True:

        sentence		= [
            choose_article(),
            choose_adjective(),
            choose_noun(),
            choose_verb(),
            choose_adverb(),
        ]

        if random.random() < lolz_chance():
            sentence.insert(random.randint(0,len(sentence)-1),choose_lol())

        print("(%d) %s." % (
            count,
            ' '.join(sentence)
        ))

        handle_input()

        count			+= 1

def handle_input():
    input			= sys.stdin.readline()
    input			= input.rstrip()
    if input == 's' or input == 'S':
        run_game()
    elif input == 'c' or input == 'r':
        os.system("clear")
        display_credits()
        run_game()
    elif input == 'h' or input == '?':
        display_help()
        run_game()
    elif input == 'l' or input == 'L':
        global lolz_mode
        lolz_mode		= not lolz_mode
        run_game()
    elif input == 'm' or input == 'M':
        display_menu()
        handle_input()
    elif input == 'o' or input == 'O':
        display_options()
        display_menu()
        handle_input()
    elif input == 'q':
        exit()

def choose_from_list(list):
    return list[random.randint(0,len(list)-1)]

def choose_noun():
    return choose_from_list(nouns)

def choose_article():
    return choose_from_list(articles)

def choose_verb():
    return choose_from_list(verbs)

def choose_adjective():
    return choose_from_list(adjectives)

def choose_adverb():
    return choose_from_list(adverbs)

def choose_preposition():
    return choose_from_list(prepositions)

def choose_prep_noun():
    return choose_from_list(prep_nouns)

def choose_lol():
    return '-- ' + choose_from_list(LOLZ) + '! --' 

def display_credits():
    print("-=[ Rand-a-Sentence ]=-\n%s" % (version))
    sys.stdin.readline()
    print("""Progamming and ideas 
by Nerf259 & mANIApHOBIC""")
    sys.stdin.readline()

def display_menu():
    print("""
[ MENU ]

(S)tart game
(H)elp
(O)ptions
(Q)uit


-=[ News ]=-
Recent updates: LOLZ Mode and Menu added!!
Upcoming updates: Achevements.
""")

def display_help():
    print("""-=[ Help ]=-

This application displays random sentences.


Controls:

    - Press Enter to see the next.
    - Press c+Enter or r+Enter to reset.
    - Press m+Enter to view the menu.
    - Press l+Enter to toggle LOLZ mode.
    - Press h+Enter or ?+Enter to display this help.
    - Press q+Enter to quit.

Press Enter to continue.
""")
    sys.stdin.readline()
    os.system("clear")

def display_options():
    print("""[ OPTIONS ]

LOLZ mode is %d
"""  % (lolz_mode))

def lolz_chance():
    chance			= 0.03
    if lolz_mode:
        chance			= 1.0
    return chance

#
#
#

lolz_mode			= False

display_credits()
display_menu()
handle_input()

