#!/usr/bin/python3

#
#
#

import os
import random
import sys

#
#
#

version				= 'InDev Version 2'

nouns				= [
    'milkshake',
    'rock',
    'barbequeue',
    'brontosaurus',
    'Tyrannosaurus Rex',
    'soda',
    'microwave',
    'oven',
    'toilet',
    'sink',
    'TV',
    'camera',
    'Cheerios',
    'airplane',
    'nose',
    'egg',
    'heat',
    'bunny',
    'chainsaw',
    'flamethrower',
    'binoculars',
    'telescope',
    'iPod',
    'clock',
    'fireplace',
    'big rig',
    'truck',
    'car',
    'iPad',
    'newspaper',
    'printer',
]

verbs				= [
    'explodes',
    'flies',
    'falls',
    'crawls',
    'crashes',
    'flushes',
    'overflows',
    'bloats',
    'shrieks',
    'eats',
    'grills',
    'ages',
    'bursts',
    'burns',
    'holds',
    'wields',
    'cooks',
    'reads',
    'gasps',  
]

adjectives			= [
    'delicious',
    'pointy',
    'bright',
    'ugly',
    'stupid',
    'poor',
    'expensive',
    'moist',
    'runny',
    'metallic',
    'hairy',
    'moldy',
    'tubular',
    'extreme',  
    
]




adverbs				= [
    'outrageously',
    'mathematically',
    'unwisely',
    'wisely',
    'blindly',
    'weakly',
    'strongly',
    'pathetically',
    'theoretically',
    'mysteriously',
    'provocatively',
    'stunningly',
    'magically',
    'wildly',
    'logically',
    'illogically',
]

articles			= [
    'The',
    'Your',
    "Your mother's",
    "Your father's",
    "Your sister's",
    "Your brother's",
    'My',
    "Your grandmother's",
    "Your grandfather's",
]

prepositions			= [
    'into',
    'out of',
]

prep_nouns			= [
    'pieces',
    'flames'
]

LOLZ				= [
    'LOLZ',
    'Kit kat',
    'EPICNESS',
    'BANANAZ',
    'PEANUT BUTER JELLY TIME!!',
    'CHEZBURGER',
    'CREEPERS GONA CREEP',
    'BLENDERZ',
    'VEGIBURGERZ',
]
#
#
#

def choose_from_list(list):
    return list[random.randint(0,len(list)-1)]

def choose_noun():
    return choose_from_list(nouns)

def choose_article():
    return choose_from_list(articles)

def choose_verb():
    return choose_from_list(verbs)

def choose_adjective():
    return choose_from_list(adjectives)

def choose_adverb():
    return choose_from_list(adverbs)

def choose_preposition():
    return choose_from_list(prepositions)

def choose_prep_noun():
    return choose_from_list(prep_nouns)

def choose_lol():
    return choose_from_list(LOLZ)

def display_credits():
    print("-=[ Rand-a-Sentence ]=-\n%s" % (version))
    sys.stdin.readline()
    print("""Progamming and ideas 
by Nerf259 & mANIApHOBIC""")
    sys.stdin.readline()

def display_help():
    print("""-=[ Help ]=-

This application displays random sentences.
Recent Updates: LOLZ Words randomly inserted.
Upcoming updates: Menu and Achevements.

Controls:

    - Press Enter to see the next.
    - Press c+Enter or r+Enter to reset.
    - Press h+Enter or ?+Enter to display this help.
    - Press q+Enter to quit.

Press Enter to continue.
""")
    sys.stdin.readline()
    os.system("clear")

#
#
#

display_credits()
display_help()

count				= 1

while True:

    sentence			= [
        choose_article(),
        choose_adjective(),
        choose_noun(),
        choose_verb(),
        choose_adverb(),
    ]

    if random.random() < 0.03:
        sentence.insert(random.randint(0,len(sentence)-1),choose_lol())

    print("(%d) %s." % (
        count,
        ' '.join(sentence)
    ))

    input			= sys.stdin.readline()

    if input == "c\n" or input == "r\n":
        os.system("clear")
        count			= 0
        display_credits()
    elif input == "h\n" or input == "?\n":
        display_help()
    elif input == "q\n":
        exit()

    count			+= 1





